name: Build Docs Website

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - website/**
      - .github/workflows/build.docs-website.yml

env:
  # Configure these
  node-version: "20"
  package: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.12
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: pnpm
      - run: pnpm i --frozen-lockfile --filter ${{ env.CI_package }}
      - run: pnpm --filter ${{ env.CI_package }} build
