name: Publish HutchController binaries

on:
  push:
    branches: [main]
    paths:
      - app/DummyControllerApi/**
      - .github/workflows/release.DummyControllerApi.yml

env:
  namespace: hutchstack
  repo-name: dummy-controller-api

jobs:
# TODO: We should publish .NET Binaries like we do for Hutch Agent, and then also build and push granularly tagged (e.g. commit hash) container images OF THOSE BINARIES
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.namespace }}/${{ env.repo-name }}
          tags: |
            ${{ github.sha }}
            latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: app/DummyControllerApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
