name: Release to Docker Hub

on:
  push:
    branches: [main]
    paths:
      - app/DummyControllerApi/**
      - .github/workflows/release.DummyControllerApi.yml

env:
  namespace: hutchstack
  repo-name: dummy-controller-api

jobs:
# TODO: this shouldn't build like it does today; it should:
# - generate a github release with a given publish run's assets
# - tag the publish run's container image as a human version matching the github release
# - optionally tag the github release and container image as `latest`
# this will better match the HutchAgent publish/release model, and will be binary atomic from the point of publish.
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.namespace }}/${{ env.repo-name }}
          tags: |
            ${{ github.sha }}
            latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: app/DummyControllerApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
